print("##############################")
print("#                            #")
print("#   Muhammad Rizki Saputra   #")
print("#       231017310014         #")
print("#                            #")
print("##############################")