Nama = input("Nama:")
NIM = input("NIM:")
Kelas_Paralel = input("Kelas Paralel:")
Tempat_Tanggal_Lahir = input("Tempat/Tanggal Lahir:")
Alamat = input("Alamat:")
Hobby = input("Hobby:")
No_HP = input("No.HP:")

print("\n")
print("Nama: ", Nama)
print("NIM:", NIM)
print("Kelas Paralel:",Kelas_Paralel)
print("Tempat/Tanggal Lahir:",Tempat_Tanggal_Lahir)
print("Alamat:",Alamat)
print("Hobby:",Hobby)
print("No.HP:",No_HP)